# Deployment for World Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
        - name: world
          image: vinutapatil/world-service:latest
          ports:
            - containerPort: 8080

---
# Service for World Service
apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  type: NodePort
  selector:
    app: world
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
